package FindDifference_389;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then
 * add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Solution {
    // naive map solution.
    // just like problem "Ransom Note"
    public char findTheDifference(String s, String t) {
        int[] map = new int[26];
        for(char c:s.toCharArray()) ++map[c-'a'];
        for(char c:t.toCharArray())
            if(--map[c-'a']<0)
                return c;
        return 0;
    }

    // bitwise solution
    // O(1) space
    public char findTheDifference2(String s, String t){
        int rs = 0;
        for(char c:s.toCharArray()) rs^=c;
        for(char c:t.toCharArray()) rs^=c;
        return (char)rs;
    }
}
