//
//  main.cpp
//  FindTheDifference_389
//
//  Created by Wenzhe Lu on 2018/3/1.
//  Copyright © 2018年 Wenzhe Lu. All rights reserved.
//

//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.

#include <string>

using std::string;

// brainstorming
// how many solution could there be??
// most intuitive: using set
// think of chars as integers, then
// it's like one more integer in array t
// then you can use sum/bit manipulation solutions
// what else?? Nothing...
class Solution {
public:
    char findTheDifference(string s, string t) {
        char rs = 0;
        for (char& c : t) rs ^= c;
        for (char& c : s) rs ^= c;
        return rs;
    }
};

int main(int argc, const char * argv[]) {
    return 0;
}
